### PR TITLE
More EP600 values

### PR DESCRIPTION
**Pull request by KM011092**
Added (nearly all) EP600 values displayed in the Bluetti App. No switches and settings.

Two issues I was not able to solve:
1.  Grid power does not differentiate if power is pulled from or pushed to the grid. I could not figure out how the BLUETTI app knows in which direction the power goes. Since I also have this information including the pull/feed information directly from my electricity meter in Home Assistant, I am using this instead.
2. Grid and AC (consumption) voltage and current for the different phase will need to be multiplied by 0.1 to show correct. Since I could not figure out how to do that in python, I created a sensor template in home assistant

### CODE REVIEW

**Comment by Patrick762** [comment]
Have you also found the ADL400 registers for AC solar? If I saw it correctly, they should be at `1228` - `1245`

**Comment by KM011092** [comment]
No, I don‘t have an ADL400.Am 14.08.2023 um 19:51 schrieb Patrick762 ***@***.***>:﻿
Have you also found the ADL400 registers for AC solar? If I saw it correctly, they should be at 1228 - 1245

**Comment by smai86** [comment]
I also get a new EP600 yesterday. I think I use it the same way as @Patrick762 with an external inverter (with ADL400 SmartMeter). @KM011092 is it possible to get these data? Actually I am using the version from @warhammerkid. How get I update to the version from @KM011092 to get more data from my EP600?

**Comment by KM011092** [comment]
I am not using an external converter, so my configuration is without the ADL400. Without an ADL400 connected I don’t know if how I can discover and add the ADL data.Am 12.12.2023 um 20:47 schrieb smai86 ***@***.***>:﻿
I also get a new EP600 yesterday. I think I use it the same way as @Patrick762 with an external inverter (with ADL400 SmartMeter). @KM011092 is it possible to get these data? Actually I am using the version from @warhammerkid. How get I update to the version from @KM011092 to get more data from my EP600?

**Comment by KM011092** [comment]
Closing since this version will not work anymore after EP600 update and Bluetooth ID for EP600 is now PBOX

**Comment by Patrick762** [comment]
Thanks for the info. Seems like it also causes my integration to no longer work. The only option I see right now is to differentiate between devices by their device_type fields

**Comment by KM011092** [comment]
Fixed the PBOX issue yesterday by adding another device called PBOX. I don’t know if the updated code only works with PBOX now, so installation is at own risk. I also did a guess on adding the ADL400 values. Not tested and no guarantee. Feel free to install the fork I’ve created or check the code I used. Since this became very specific to PBOX/EP600 I will not raise a pull request again. I am also not planning to add more registers, since I have all the info I need.

**Pull request closed without merging**
