### PR TITLE
Most fields should now be exported to Home Assistant

### LINKED ISSUE #37: Batterypack Details
Hi there,

this is not really an issue, just the question about extended function. I'm using AC200MAX extended with two batterypacks. 
Currently there is only the total_battery_percent delivered to Homeassitant.
I just seen via MQTT explorer that the Battery details are already read out and available via MQTT:

pack_details2 = {"percent":58,"voltages":[3.37,3.37,3.37,3.37,3.37,3.37,3.37,3.37,3.37,3.37,3.37,3.37,3.37,3.37,3.37,3.37]}
pack_details3 = {"percent":53,"voltages":[3.38,3.38,3.38,3.38,3.38,3.38,3.38,3.38,3.38,3.38,3.38,3.38,3.38,3.38,3.38,3.38]}
pack_details1 = {"percent":35,"voltages":[3.38,3.38,3.38,3.38,3.38,3.38,3.38,3.38,3.38,3.38,3.38,3.38,3.38,3.38,3.38,3.38]}

I there a possibility to have the charging percentage of each Battery also available within Homeassistant?

Regards and greetings from Germany
Michael

PS: Great work so far and very useful tool for all HA and Bluetti useres.

### PR DESCRIPTION
**Pull request by warhammerkid**
Rather than continue to get individual requests for specific fields to be added for Home Assistant, I'm going ahead and just adding (almost) everything. Battery cell voltages are currently not being exported even under the advanced flag, but I might change my mind about this if I get requests.

Fixes #37 & #42

### CODE REVIEW

**Comment by warhammerkid** [comment]
I'm pretty sure the battery pack details aren't working for some reason, so I still need to do another QA pass of this.

**Comment by slash5k1** [comment]
Fantastic work! 

As a suggestion would you be better off keeping the mqtt_client library "pure" and focused on connecting, publishing and listening for messages and have a home assistant library that all this good work can move in to ?

**Comment by slash5k1** [comment]
Can we also have a button type to support power_off.

By publishing a button with a payload_press
```
            await client.publish(
                f'homeassistant/button/{d.sn}_power_off/config',
                payload=payload(
                    id='power_off',
                    device=d,
                    name='Power Off',
                    payload_press': "ON"
                ).encode(),
                retain=True
            )
```
I can have a button you press that switches off the device:
PowerOff

**Comment by warhammerkid** [comment]
> Can we also have a button type to support power_off.

@slash5k1 That's an excellent suggestion. Done!

> As a suggestion would you be better off keeping the mqtt_client library "pure" and focused on connecting, publishing and listening for messages and have a home assistant library that all this good work can move in to ?

@slash5k1 I suspect if/when a full Home Assistant add-on is available that it will no longer be needed to provide Home Assistant MQTT config in this package. I did consider pulling the Home Assistant stuff out into a separate file, but it would have just made things more complicated to maintain.

**Comment by steveheinsch** [comment]
> Battery cell voltages are currently not being exported even under the advanced flag, but I might change my mind about this if I get requests.

Here's a vote for providing the individual battery cell data :) Living off the grid, it's essential to know if a cell is starting to go bad and trigger alarms, etc.

**Pull request merged**
