### PR TITLE
Updated homeassistant MQTT discovery

### PR DESCRIPTION
**Pull request by slash5k1**
Added support for homeassistant to discover the percent of each battery pack

### CODE REVIEW

**Comment by slash5k1** [comment]
Needs to be tested against homeassistant to see if the value_template": "{{ value_json.percent }} works as described in the ha docs - https://www.home-assistant.io/integrations/mqtt/#mqtt-discovery

**Comment by slash5k1** [comment]
Tested against Home Assistant release 2022.11:
HA testing screenshot
HA testing screenshot 2

**Comment by slash5k1** [comment]
Can see this work is being cleaned up under #45

**Comment by warhammerkid** [comment]
I'm going to close this now that #45 is merged, which adds battery pack details (among other things).

**Pull request closed without merging**
